### ISSUE TITLE
about using GSL library

### ISSUE THREAD

**Issue by itisabook** [kkentzo/pso#1]
Hi,
Sorry to bother you, I'm a newbie so hopefully my question won't make you unconfortable.

I want to try to merge your PSO function into mine, what I want to do is using PSO to find optimal parameters of GMM which can differentiates foreground object from background.
But my question is can I use your PSO function without GSL library? I find that you use GSL for random number generation. Is that necessary to use GSL? Or could I just use rand() in C ?

Thanks for your help.
Lou

**Comment by kkentzo** [comment]
Hi, 

yes, the only thing gsl is used for is generating random numbers, so you can substitute gsl_\* calls with rand() or any other method you prefer.

Kyriakos
