### ISSUE TITLE
Regarding the Griewank Function

### ISSUE THREAD

**Issue by duaraghav8** [kkentzo/pso#2]
Hey,
I'm learning PSO these days and your library has been extremely helpful in clarifying some doubts I had. However, I see that you use sqrt (i + 1) in the Griewank Function definition, whereas the actual definition uses sqrt (i).

When i use sqrt (i) in my implementation, it always elicits -nan, but yields a value when sqrt (i + 1) is used. Why did you use sqrt (i + 1)?

Regards

**Comment by kkentzo** [comment]
Hi there. It's sqrt(i+1) because the iteration in the loop starts at i=0 (i is used to index the incoming vector). In the actual definition, the iteration starts at 1, that's why it uses sqrt(i).
