### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by zkccpro** [kkentzo/pso#3]
Hi,I use Ubantu to run your pso code,I've already set on gsl.But there is still a bug in pso.h-264:

// allocate the RNG
    settings->rng = gsl_rng_alloc(gsl_rng_default);

Error message is :  identifier "gsl_rng_default" is undefined.

**Comment by kkentzo** [comment]
Hello!

a few things to check out:

* is `libgsl` correctly installed and discoverable by the compiler?
* have you included the `-lgsl` switch in your build command? (if you've used the Makefile it's already included)

If you keep encountering problems, I would recommend removing all `gsl` references and use the [rand() function](http://www.cplusplus.com/reference/cstdlib/rand/) from C standard library (or some other library for that matter).

**Comment by kkentzo** [comment]
I've now pushed a commit in master that removes the `libgsl` dependency. This should solve your issue.

**Comment by zkccpro** [comment]
Ok,thanks. I have already fixed my problem. I didn’t set my libgsl correctly. 

发送自 Windows 10 版邮件应用

发件人: Kyriakos Kentzoglanakis
发送时间: 2020年3月16日 4:52
收件人: kkentzo/pso
抄送: zkccnb; Author
主题: Re: [kkentzo/pso] A problem (#3)

I've now pushed a commit in master that removes the libgsl dependency. This should solve your issue.

**Comment by zkccpro** [comment]
Hi, now I have a C++ code, which has some paramters need to optimal with PSO.
I want to know whether your pso code can compatible with C++ code?(I notice your pso-master is written by C)
And how can I build your code with my project(C++code) together on linux?(I use Vscode-GNU-GDB, Will I need special compile command?)
This may be my first linux project, so there are lots of things I don’t know well, so Thank you very much!!!


发送自 Windows 10 版邮件应用

发件人: Kyriakos Kentzoglanakis
发送时间: 2020年3月16日 4:52
收件人: kkentzo/pso
抄送: zkccnb; Author
主题: Re: [kkentzo/pso] A problem (#3)

I've now pushed a commit in master that removes the libgsl dependency. This should solve your issue.

**Comment by kkentzo** [comment]
Yes, you should be able to include the 2 pso files (pso.h and pso.c) in your C++ code as is. 

No special command is needed - just include these two files along with your other files and build your C++ project as you normally would.

**Comment by zkccpro** [comment]
Ok,thanks. I will try it next.
发送自 Windows 10 版邮件应用

发件人: Kyriakos Kentzoglanakis
发送时间: 2020年3月18日 16:27
收件人: kkentzo/pso
抄送: zkccnb; Author
主题: Re: [kkentzo/pso] A problem (#3)

Yes, you should be able to include the 2 pso files (pso.h and pso.c) in your C++ code as is.
No special command is needed - just include these two files along with your other files and build your C++ project as you normally would.

**Comment by zkccpro** [comment]
Hello, now I have already added your code to my project and it shows well so far.
Since, I have read your code, I find I do not understand the neighborhood strategy and 
linearly decreasing inertia weight strategy very well.
Besides, I check your link:
http://clerc.maurice.free.fr/pso/random_topology.pdf**
but it is invalid by now in my area.
So I want to know if you have some paper about PSO or the strategies you used in your pso code? If you have some PDF files, please send me by email.
Thank you very much! During the epidemic situation, don’t forget to stay at home and wear on a mask if necessry. Hope for you and your family in health!
发送自 Windows 10 版邮件应用

发件人: Kyriakos Kentzoglanakis
发送时间: 2020年3月18日 16:27
收件人: kkentzo/pso
抄送: zkccnb; Author
主题: Re: [kkentzo/pso] A problem (#3)

Yes, you should be able to include the 2 pso files (pso.h and pso.c) in your C++ code as is.
No special command is needed - just include these two files along with your other files and build your C++ project as you normally would.

**Comment by kkentzo** [comment]
Hello. Thank you for your wishes.

Maurice Clerc's article link works fine for me. [Here is the pdf](https://github.com/kkentzo/pso/files/4386267/random_topology.pdf).

Unfortunately, after all these years I do not have the pdf versions of the other articles (and most of them are behind paywalls as far as I can see). You can search [here](https://arxiv.org/) for free alternative resources. Good luck!
