### ISSUE TITLE
Request for separate variable boundaries/limits

### ISSUE THREAD

**Issue by dionkaridis** [kkentzo/pso#4]
Could you please implement separate boundaries for each variable in the code?
This could be very useful for many problems which require 
separate limitations for the variables involved.

Thanks in advance,
Dionysis Karydis.

**Comment by kkentzo** [comment]
This has now been implemented. Please try it out and re-open this issue if you encounter any problems.

**Comment by dionkaridis** [comment]
Thank you so much.
I noticed that the new code is compatible with a gcc compiler but not with a g++ one. This might be because you use .c and not .cpp files. This brings about incompatibilities with Fitness Functions that are implemented totally in C++. The basic issue here is the use of 'malloc' as well as some minor problems.

**Comment by kkentzo** [comment]
Please fetch and try again. With commit 59d02c3, I am able to build the demo program successfully using a c++ compiler with the command: `g++ -v -o demo demo.c pso.c`.

I am using clang on Mac OS but it should work on any platform.

Please try it and feel free to report back if you have new issues!

**Comment by dionkaridis** [comment]
Thank you so much. It worked just fine. 
Now everyone working on C++ can implement this code without any problem.
